// Code generated by gen-go-proxy. DO NOT EDIT.
// source: /home/issuh/workspace/my_project/gen-go-proxy/example/proxy/service/foo.go

package service

import "context"

const (
	proxyAnnotationKeyOnFoo   string = "proxy"
	custom2AnnotationKeyOnFoo string = "custom2"
	custom1AnnotationKeyOnFoo string = "custom1"
)

// helper for FooProxy middleware
type FooProxyMiddleware func(func(context.Context) error) func(context.Context) error
type FooProxyMiddlewares []FooProxyMiddleware

// convert FooProxy middleware to raw type
func (a FooProxyMiddlewares) To() []func(func(context.Context) error) func(context.Context) error {
	m := []func(func(context.Context) error) func(context.Context) error{}
	for _, v := range a {
		m = append(m, v)
	}
	return m
}

// helper for FooProxy middleware map about middlewares by aannotation
type FooProxyMiddlewareByAnnotation map[string]FooProxyMiddlewares

// convert FooProxy middleware map to raw type
func (a FooProxyMiddlewareByAnnotation) To() map[string][]func(func(context.Context) error) func(context.Context) error {
	m := map[string][]func(func(context.Context) error) func(context.Context) error{}
	for key, value := range a {
		m[key] = value.To()
	}
	return m
}

// implement proxy for Foo
type FooProxy struct {
	target             Foo
	proxyMiddlewares   []func(func(context.Context) error) func(context.Context) error
	custom2Middlewares []func(func(context.Context) error) func(context.Context) error
	custom1Middlewares []func(func(context.Context) error) func(context.Context) error
}

func NewFooProxy(target Foo, middlewares map[string][]func(func(context.Context) error) func(context.Context) error) *FooProxy {
	p := &FooProxy{
		target: target,
	}

	for key, value := range middlewares {
		switch key {

		case proxyAnnotationKeyOnFoo:
			p.proxyMiddlewares = value
		case custom2AnnotationKeyOnFoo:
			p.custom2Middlewares = value
		case custom1AnnotationKeyOnFoo:
			p.custom1Middlewares = value
		}
	}

	return p
}

func (p *FooProxy) Logic(needEmitErr bool) (string, error) {
	var (
		r0  string
		err error
	)

	f := func(context.Context) error {
		r0, err = p.target.Logic(needEmitErr)
		if err != nil {
			return err
		}
		return nil
	}

	for i := range p.proxyMiddlewares {
		index := len(p.proxyMiddlewares) - i - 1
		f = p.proxyMiddlewares[index](f)
	}

	f(context.TODO())
	return r0, err
}

func (p *FooProxy) Foo() int {
	var (
		r0 int
	)

	f := func(context.Context) error {
		r0 = p.target.Foo()
		return nil
	}

	for i := range p.custom2Middlewares {
		index := len(p.custom2Middlewares) - i - 1
		f = p.custom2Middlewares[index](f)
	}

	for i := range p.custom1Middlewares {
		index := len(p.custom1Middlewares) - i - 1
		f = p.custom1Middlewares[index](f)
	}

	f(context.TODO())
	return r0
}

const (
	proxyAnnotationKeyOnBar   string = "proxy"
	custom2AnnotationKeyOnBar string = "custom2"
	custom1AnnotationKeyOnBar string = "custom1"
)

// helper for BarProxy middleware
type BarProxyMiddleware func(func(context.Context) error) func(context.Context) error
type BarProxyMiddlewares []BarProxyMiddleware

// convert BarProxy middleware to raw type
func (a BarProxyMiddlewares) To() []func(func(context.Context) error) func(context.Context) error {
	m := []func(func(context.Context) error) func(context.Context) error{}
	for _, v := range a {
		m = append(m, v)
	}
	return m
}

// helper for BarProxy middleware map about middlewares by aannotation
type BarProxyMiddlewareByAnnotation map[string]BarProxyMiddlewares

// convert BarProxy middleware map to raw type
func (a BarProxyMiddlewareByAnnotation) To() map[string][]func(func(context.Context) error) func(context.Context) error {
	m := map[string][]func(func(context.Context) error) func(context.Context) error{}
	for key, value := range a {
		m[key] = value.To()
	}
	return m
}

// implement proxy for Bar
type BarProxy struct {
	target             Bar
	proxyMiddlewares   []func(func(context.Context) error) func(context.Context) error
	custom2Middlewares []func(func(context.Context) error) func(context.Context) error
	custom1Middlewares []func(func(context.Context) error) func(context.Context) error
}

func NewBarProxy(target Bar, middlewares map[string][]func(func(context.Context) error) func(context.Context) error) *BarProxy {
	p := &BarProxy{
		target: target,
	}

	for key, value := range middlewares {
		switch key {

		case proxyAnnotationKeyOnBar:
			p.proxyMiddlewares = value
		case custom2AnnotationKeyOnBar:
			p.custom2Middlewares = value
		case custom1AnnotationKeyOnBar:
			p.custom1Middlewares = value
		}
	}

	return p
}

func (p *BarProxy) Logic(needEmitErr bool) (string, error) {
	var (
		r0  string
		err error
	)

	f := func(context.Context) error {
		r0, err = p.target.Logic(needEmitErr)
		if err != nil {
			return err
		}
		return nil
	}

	for i := range p.proxyMiddlewares {
		index := len(p.proxyMiddlewares) - i - 1
		f = p.proxyMiddlewares[index](f)
	}

	f(context.TODO())
	return r0, err
}

func (p *BarProxy) Foo() int {
	var (
		r0 int
	)

	f := func(context.Context) error {
		r0 = p.target.Foo()
		return nil
	}

	for i := range p.custom2Middlewares {
		index := len(p.custom2Middlewares) - i - 1
		f = p.custom2Middlewares[index](f)
	}

	for i := range p.custom1Middlewares {
		index := len(p.custom1Middlewares) - i - 1
		f = p.custom1Middlewares[index](f)
	}

	f(context.TODO())
	return r0
}
