// Code generated by simple-gen-proxy. DO NOT EDIT.
// source: ./example/service/bar.go

package proxy

import (
	"context"

	"github.com/ISSuh/simple-gen-proxy/example/dto"

	entity "github.com/ISSuh/simple-gen-proxy/example/entity"

	service "github.com/ISSuh/simple-gen-proxy/example/service"
)

type BarProxyTxHelper func(c context.Context, f func(c context.Context) error)

type BarProxy struct {
	target service.Bar
	tx     BarProxyTxHelper
}

func NewBarProxy(target service.Bar, tx BarProxyTxHelper) *BarProxy {
	return &BarProxy{
		target: target,
		tx:     tx,
	}
}

func (p *BarProxy) Create(_userCtx context.Context, dto dto.Bar) (int, error) {
	var (
		r0  int
		err error
	)

	p.tx(_userCtx, func(_helperCtx context.Context) error {
		r0, err = p.target.Create(_helperCtx, dto)
		if err != nil {
			return err
		}
		return nil
	})

	return r0, err
}

func (p *BarProxy) Find(_userCtx context.Context, id int) (*entity.Bar, error) {
	return p.target.Find(_userCtx, id)
}
