// Code generated by simple-gen-proxy. DO NOT EDIT.
// source: /home/issuh/workspace/my_project/gen-tx-proxy/example/transaction/service/bar.go

package proxy

import (
	"context"

	"github.com/ISSuh/simple-gen-proxy/example/transaction/dto"
	entity "github.com/ISSuh/simple-gen-proxy/example/transaction/entity"
	service "github.com/ISSuh/simple-gen-proxy/example/transaction/service"
)

type BarProxyMiddleware func(func(context.Context) error) func(context.Context) error

type BarProxy struct {
	target      service.Bar
	middlewares []BarProxyMiddleware
}

func NewBarProxy(target service.Bar, middlewares ...BarProxyMiddleware) *BarProxy {
	return &BarProxy{
		target:      target,
		middlewares: middlewares,
	}
}

func (p *BarProxy) Create(_userCtx context.Context, dto dto.Bar) (int, error) {
	var (
		r0  int
		err error
	)

	f := func(_helperCtx context.Context) error {
		r0, err = p.target.Create(_helperCtx, dto)
		if err != nil {
			return err
		}
		return nil
	}

	for i := range p.middlewares {
		index := len(p.middlewares) - i - 1
		f = p.middlewares[index](f)
	}

	f(_userCtx)
	return r0, err
}

func (p *BarProxy) Find(_userCtx context.Context, id int) (*entity.Bar, error) {
	return p.target.Find(_userCtx, id)
}
