// Code generated by gen-go-proxy. DO NOT EDIT.
// source: /home/issuh/workspace/my_project/gen-go-proxy/example/transaction/service/foo.go

package proxy

import (
	"context"

	"github.com/ISSuh/gen-go-proxy/example/transaction/dto"
	entity "github.com/ISSuh/gen-go-proxy/example/transaction/entity"
	service "github.com/ISSuh/gen-go-proxy/example/transaction/service"
)

const (
	transactionalAnnotationKeyOnFoo string = "transactional"
)

// helper for FooProxy middleware
type FooProxyMiddleware func(func(context.Context) error) func(context.Context) error
type FooProxyMiddlewares []FooProxyMiddleware

// convert FooProxy middleware to raw type
func (a FooProxyMiddlewares) To() []func(func(context.Context) error) func(context.Context) error {
	m := []func(func(context.Context) error) func(context.Context) error{}
	for _, v := range a {
		m = append(m, v)
	}
	return m
}

// helper for FooProxy middleware map about middlewares by aannotation
type FooProxyMiddlewareByAnnotation map[string]FooProxyMiddlewares

// convert FooProxy middleware map to raw type
func (a FooProxyMiddlewareByAnnotation) To() map[string][]func(func(context.Context) error) func(context.Context) error {
	m := map[string][]func(func(context.Context) error) func(context.Context) error{}
	for key, value := range a {
		m[key] = value.To()
	}
	return m
}

// implement proxy for Foo
type FooProxy struct {
	target                   service.Foo
	transactionalMiddlewares []func(func(context.Context) error) func(context.Context) error
}

func NewFooProxy(target service.Foo, middlewares map[string][]func(func(context.Context) error) func(context.Context) error) *FooProxy {
	p := &FooProxy{
		target: target,
	}

	for key, value := range middlewares {
		switch key {

		case transactionalAnnotationKeyOnFoo:
			p.transactionalMiddlewares = value
		}
	}

	return p
}

func (p *FooProxy) Create(_userCtx context.Context, dto dto.Foo) (int, error) {
	var (
		r0  int
		err error
	)

	f := func(_helperCtx context.Context) error {
		r0, err = p.target.Create(_helperCtx, dto)
		if err != nil {
			return err
		}
		return nil
	}

	for i := range p.transactionalMiddlewares {
		index := len(p.transactionalMiddlewares) - i - 1
		f = p.transactionalMiddlewares[index](f)
	}

	f(_userCtx)
	return r0, err
}

func (p *FooProxy) Find(_userCtx context.Context, id int) (*entity.Foo, error) {
	return p.target.Find(_userCtx, id)
}

func (p *FooProxy) FooBara(_userCtx context.Context, dto dto.Foo) error {
	var (
		err error
	)

	f := func(_helperCtx context.Context) error {
		err = p.target.FooBara(_helperCtx, dto)
		if err != nil {
			return err
		}
		return nil
	}

	for i := range p.transactionalMiddlewares {
		index := len(p.transactionalMiddlewares) - i - 1
		f = p.transactionalMiddlewares[index](f)
	}

	f(_userCtx)
	return err
}

const (
	transactionalAnnotationKeyOnFoo2 string = "transactional"
)

// helper for Foo2Proxy middleware
type Foo2ProxyMiddleware func(func(context.Context) error) func(context.Context) error
type Foo2ProxyMiddlewares []Foo2ProxyMiddleware

// convert Foo2Proxy middleware to raw type
func (a Foo2ProxyMiddlewares) To() []func(func(context.Context) error) func(context.Context) error {
	m := []func(func(context.Context) error) func(context.Context) error{}
	for _, v := range a {
		m = append(m, v)
	}
	return m
}

// helper for Foo2Proxy middleware map about middlewares by aannotation
type Foo2ProxyMiddlewareByAnnotation map[string]Foo2ProxyMiddlewares

// convert Foo2Proxy middleware map to raw type
func (a Foo2ProxyMiddlewareByAnnotation) To() map[string][]func(func(context.Context) error) func(context.Context) error {
	m := map[string][]func(func(context.Context) error) func(context.Context) error{}
	for key, value := range a {
		m[key] = value.To()
	}
	return m
}

// implement proxy for Foo2
type Foo2Proxy struct {
	target                   service.Foo2
	transactionalMiddlewares []func(func(context.Context) error) func(context.Context) error
}

func NewFoo2Proxy(target service.Foo2, middlewares map[string][]func(func(context.Context) error) func(context.Context) error) *Foo2Proxy {
	p := &Foo2Proxy{
		target: target,
	}

	for key, value := range middlewares {
		switch key {

		case transactionalAnnotationKeyOnFoo2:
			p.transactionalMiddlewares = value
		}
	}

	return p
}

func (p *Foo2Proxy) Create(_userCtx context.Context, dto dto.Foo) (int, error) {
	var (
		r0  int
		err error
	)

	f := func(_helperCtx context.Context) error {
		r0, err = p.target.Create(_helperCtx, dto)
		if err != nil {
			return err
		}
		return nil
	}

	for i := range p.transactionalMiddlewares {
		index := len(p.transactionalMiddlewares) - i - 1
		f = p.transactionalMiddlewares[index](f)
	}

	f(_userCtx)
	return r0, err
}

func (p *Foo2Proxy) Find(_userCtx context.Context, id int) (*entity.Foo, error) {
	return p.target.Find(_userCtx, id)
}

func (p *Foo2Proxy) FooBara(_userCtx context.Context, dto dto.Foo) error {
	var (
		err error
	)

	f := func(_helperCtx context.Context) error {
		err = p.target.FooBara(_helperCtx, dto)
		if err != nil {
			return err
		}
		return nil
	}

	for i := range p.transactionalMiddlewares {
		index := len(p.transactionalMiddlewares) - i - 1
		f = p.transactionalMiddlewares[index](f)
	}

	f(_userCtx)
	return err
}
