// Code generated by simple-gen-proxy. DO NOT EDIT.
// source: example/proxy/service/foo.go

package proxy

import (
	"context"

	service "github.com/ISSuh/simple-gen-proxy/example/proxy/service"
)

type FooProxyHelper func(c context.Context, f func(c context.Context) error) error

type FooProxy struct {
	target service.Foo
	helper FooProxyHelper
}

func NewFooProxy(target service.Foo, helper FooProxyHelper) *FooProxy {
	return &FooProxy{
		target: target,
		helper: helper,
	}
}

func (p *FooProxy) Logic(needEmitErr bool) (string, error) {
	var (
		r0  string
		err error
	)

	err = p.helper(context.Background(), func(_ context.Context) error {
		r0, err = p.target.Logic(needEmitErr)
		if err != nil {
			return err
		}
		return nil
	})

	return r0, err
}
